version: 2.1
executors:
  docker-publisher:
    docker:
      - image: docker:stable
        auth:
          username: $username
          password: $user
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build --tag test_node:lts .      
  push:
    executor: docker-publisher
    steps:
      - setup_remote_docker   
      - run:
          name: Publish Docker image
          command: |
            docker tag test_node:lts shaymaa12/test_node:lts
            docker login -u $username -p $user
            docker push shaymaa12/test_node:lts
workflows:
  version: 2
  build-push:
    jobs:
      - build:
          context: DockerHub
      - push:
          context: DockerHub
          requires:
            - build
