version: 2.1     
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
jobs:
  test:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
#       - run:
#           name: Build Image
#           command: docker build --tag $username/test_node:$CIRCLE_BUILD_NUM .
#       - run:
#           name: Login to DockerHub
#           command: echo $user | docker login -u $username --password-stdin
#       - run:
#           name: Push Image to DockerHub
#           command: docker push $username/test_node:$CIRCLE_BUILD_NUM
#       - run:
#           name: Run Container from Image
#           command: docker run -d -p 3000:3000 --name node $username/test_node:$CIRCLE_BUILD_NUM
workflows:
  version: 2
  build:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          repo: cicd
          tag: lts
          dockerfile: dockerfile
          path: .
          requires:
            - test
