version: 2.1     
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
jobs:
  test:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
  deploy:
    docker: 
      - image: docker:stable
    steps:
      - run:
          name: Login to AWS and run the Image
          command: |
            ssh -o StrictHostKeyChecking=no i- $HOME/.ssh/id_rsa ins_circle@ec2-18-234-50-11.compute-1.amazonaws.com " aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 564162621498.dkr.ecr.us-east-1.amazonaws.com &&
            sudo docker run -d -p 3000:3000 --name node 564162621498.dkr.ecr.us-east-1.amazonaws.com/cicd:latest"    
workflows:
  version: 2
  build:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          repo: cicd
          tag: latest
          dockerfile: dockerfile
          path: .
          requires:
            - test
      - deploy:
          requires: 
            - aws-ecr/build-and-push-image
