version: 2.1

executors:
  docker-publisher:
    docker:
      - image: docker:stable

jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build --tag shaymaa12/node:lts .
      
  push:
    executor: docker-publisher
    steps:
      - setup_remote_docker   
      - run:
          name: Publish Docker image
          command: |
            echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login --username "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin
            docker push shaymaa12/node:lts
workflows:
  version: 2
  build-push:
    jobs:
      - build
      - push:
          requires:
            - build
