version: 2.1

executors:
  docker-publisher:
    docker:
      - image: docker:stable

jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build --tag shaymaa12/node:lts .
      
  push:
    executor: docker-publisher
    steps:
      - setup_remote_docker   
      - run:
        name: login to Dockerhub 
        command: |
          echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - run:
        name: push to Dockerhub
        command: |
          docker push shaymaa12/node:lts
workflows:
  version: 2
  build-push:
    jobs:
      - build
      - push:
          requires:
            - build
