version: 2.1
executors:
  docker-publisher:
    docker:
      - image: docker:stable
        auth:
          username: $username
          password: $user
jobs:
  test:
    docker:
      - image: cimg/node:20.1.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: |
            docker build --tag test_node:lts .
            docker tag test_node:lts shaymaa12/test_node:lts
            docker login -u $username -p $user
            docker push shaymaa12/test_node:lts
          
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Pushing to DockerHub
          command: docker push shaymaa12/node:lts
      - run:
          name: Running Container
          command: docker run -d -p 3000:3000 --name node shaymaa12/node:lts
workflows:
  version: 2
  build-push:
    jobs:
      - test:
          context: DockerHub
