version: 2.1        
jobs:
  test:
    docker:
      - image: cimg/node:20.1.0
        auth:
          username: $username
          password: $user
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: |
            docker build --tag test_node:lts .
            docker tag test_node:lts shaymaa12/test_node:lts
            echo $user | docker login -u $username --password-stdin
            docker push shaymaa12/test_node:lts
            docker run -d -p 3000:3000 --name node shaymaa12/test_node:lts
workflows:
  version: 2
  build:
    jobs:
      - test:
          context: DockerHub
