version: 2.1
workflows:
  test-deploy:
    jobs:
      - test:
          context:
            - DockerHub
jobs:
  test:
    docker:
      - image: cimg/node:20.1.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build Image
          command: docker build -t shaymaa/node .
      - run:
          name: Login to DockerHub
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Pushing to DockerHub
          command: docker push shaymaa12/node:lts
      - run:
          name: Running Container
          command: docker run -d -p 3000:3000 --name node-app shaymaa12/node
