version: 2.1        
jobs:
  test:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build Image
          command: |
            docker build --tag shaymaa12/test_node:<<pipeline.number>> .
            echo $user | docker login -u $username --password-stdin
            docker push shaymaa12/test_node:<<pipeline.number>>
            docker run -d -p 3000:3000 --name node shaymaa12/test_node:<<pipeline.number>>
workflows:
  version: 2
  build:
    jobs:
      - test:
          context: DockerHub
