version: 2.1

executors:
  docker-publisher:
    docker:
      - image: docker:stable
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
        # installs a docker client that will be used to run the docker commands
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Docker image
          command: docker build --tag shaymaa12/node:lts .      
  push:
    executor: docker-publisher
    steps:
      - setup_remote_docker   
      - run:
          name: Publish Docker image
          command: |
            docker login -u username -p password
            docker push shaymaa12/node:lts
workflows:
  version: 2
  build-push:
    jobs:
      - build
      - push:
          requires:
            - build
